// Date: 6/11/2015 10:50:05 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelDraco Aquila extends ModelBase
{
  //fields
    ModelRenderer flyingLeftTopLeg;
    ModelRenderer flyingLeftLeg;
    ModelRenderer flyingLeftFoot;
    ModelRenderer flyingRightTopLeg;
    ModelRenderer flyingRightLeg;
    ModelRenderer flyingRightFoot;
    ModelRenderer flyingBeakTop;
    ModelRenderer flyingBeakBottom;
    ModelRenderer flyingTail;
    ModelRenderer flyingHead;
    ModelRenderer flyingBody;
    ModelRenderer flyingRightWing;
    ModelRenderer flyingLeftWing;
  
  public ModelDraco Aquila()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      flyingLeftTopLeg = new ModelRenderer(this, 400, 200);
      flyingLeftTopLeg.addBox(-2.5F, 0F, -2.5F, 5, 7, 5);
      flyingLeftTopLeg.setRotationPoint(6F, 4F, 0F);
      flyingLeftTopLeg.setTextureSize(512, 256);
      flyingLeftTopLeg.mirror = true;
      setRotation(flyingLeftTopLeg, 0.9815153F, 0F, 0F);
      flyingLeftLeg = new ModelRenderer(this, 380, 200);
      flyingLeftLeg.addBox(-1.5F, 7F, -1.5F, 3, 13, 3);
      flyingLeftLeg.setRotationPoint(6F, 4F, 0F);
      flyingLeftLeg.setTextureSize(512, 256);
      flyingLeftLeg.mirror = true;
      setRotation(flyingLeftLeg, 0.9815153F, 0F, 0F);
      flyingLeftFoot = new ModelRenderer(this, 340, 210);
      flyingLeftFoot.addBox(-5.5F, 20F, -9.5F, 11, 0, 11);
      flyingLeftFoot.setRotationPoint(6F, 4F, 0F);
      flyingLeftFoot.setTextureSize(512, 256);
      flyingLeftFoot.mirror = true;
      setRotation(flyingLeftFoot, 0.9815153F, 0F, 0F);
      flyingRightTopLeg = new ModelRenderer(this, 400, 200);
      flyingRightTopLeg.addBox(-2.5F, 0F, -2.5F, 5, 7, 5);
      flyingRightTopLeg.setRotationPoint(-6F, 4F, 0F);
      flyingRightTopLeg.setTextureSize(512, 256);
      flyingRightTopLeg.mirror = true;
      setRotation(flyingRightTopLeg, 0.9815153F, 0F, 0F);
      flyingRightLeg = new ModelRenderer(this, 380, 200);
      flyingRightLeg.addBox(-1.5F, 7F, -1.5F, 3, 13, 3);
      flyingRightLeg.setRotationPoint(-6F, 4F, 0F);
      flyingRightLeg.setTextureSize(512, 256);
      flyingRightLeg.mirror = true;
      setRotation(flyingRightLeg, 0.9815153F, 0F, 0F);
      flyingRightFoot = new ModelRenderer(this, 340, 210);
      flyingRightFoot.addBox(-5.5F, 20F, -9.5F, 11, 0, 11);
      flyingRightFoot.setRotationPoint(-6F, 4F, 0F);
      flyingRightFoot.setTextureSize(512, 256);
      flyingRightFoot.mirror = true;
      setRotation(flyingRightFoot, 0.9815153F, 0F, 0F);
      flyingBeakTop = new ModelRenderer(this, 357, 199);
      flyingBeakTop.addBox(-2.5F, 0F, -22F, 5, 1, 5);
      flyingBeakTop.setRotationPoint(0F, -4F, -30F);
      flyingBeakTop.setTextureSize(512, 256);
      flyingBeakTop.mirror = true;
      setRotation(flyingBeakTop, 0F, 0F, 0F);
      flyingBeakBottom = new ModelRenderer(this, 331, 199);
      flyingBeakBottom.addBox(-2.5F, 1F, -22F, 5, 1, 5);
      flyingBeakBottom.setRotationPoint(0F, -4F, -30F);
      flyingBeakBottom.setTextureSize(512, 256);
      flyingBeakBottom.mirror = true;
      setRotation(flyingBeakBottom, 0F, 0F, 0F);
      flyingTail = new ModelRenderer(this, 250, 222);
      flyingTail.addBox(-20F, 0F, 0F, 40, 0, 30);
      flyingTail.setRotationPoint(0F, -15F, 10F);
      flyingTail.setTextureSize(512, 256);
      flyingTail.mirror = true;
      setRotation(flyingTail, -0.4363323F, 0F, 0F);
      flyingHead = new ModelRenderer(this, 400, 158);
      flyingHead.addBox(-8.5F, -10F, -17F, 17, 17, 17);
      flyingHead.setRotationPoint(0F, -4F, -30F);
      flyingHead.setTextureSize(512, 256);
      flyingHead.mirror = true;
      setRotation(flyingHead, 0F, 0F, 0F);
      flyingBody = new ModelRenderer(this, 392, 196);
      flyingBody.addBox(-10F, -20F, -30F, 20, 20, 40);
      flyingBody.setRotationPoint(0F, 5F, 0F);
      flyingBody.setTextureSize(512, 256);
      flyingBody.mirror = true;
      setRotation(flyingBody, 0F, 0F, 0F);
      flyingRightWing = new ModelRenderer(this, 0, 194);
      flyingRightWing.addBox(-90F, -20F, -40F, 80, 0, 60);
      flyingRightWing.setRotationPoint(0F, 5F, 0F);
      flyingRightWing.setTextureSize(512, 256);
      flyingRightWing.mirror = true;
      setRotation(flyingRightWing, 0F, 0F, 0F);
      flyingLeftWing = new ModelRenderer(this, 0, 131);
      flyingLeftWing.addBox(10F, -20F, -40F, 80, 0, 60);
      flyingLeftWing.setRotationPoint(0F, 5F, 0F);
      flyingLeftWing.setTextureSize(512, 256);
      flyingLeftWing.mirror = true;
      setRotation(flyingLeftWing, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    flyingLeftTopLeg.render(f5);
    flyingLeftLeg.render(f5);
    flyingLeftFoot.render(f5);
    flyingRightTopLeg.render(f5);
    flyingRightLeg.render(f5);
    flyingRightFoot.render(f5);
    flyingBeakTop.render(f5);
    flyingBeakBottom.render(f5);
    flyingTail.render(f5);
    flyingHead.render(f5);
    flyingBody.render(f5);
    flyingRightWing.render(f5);
    flyingLeftWing.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
